---
title: "R Notebook"
author: "Eugeni Vidal"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document
---

```{r}
#load libraries
library(tidyverse)
library(dplyr)
library(psych)
library(sf)
library(tmap)
```

```{r message=FALSE, warning=FALSE, cache=FALSE, include=FALSE, paged.print=FALSE}
# load WY PCT data
## shortname for the url
#u_lsoa = "https://github.com/npct/pct-outputs-regional-notR/raw/master/commute/lsoa/west-yorkshire/z.geojson"
u_msoa = "https://github.com/npct/pct-outputs-regional-notR/raw/master/commute/msoa/west-yorkshire/z.geojson"
#download.file(url = u_lsoa, destfile = "data/z.lsoa.geojson")
download.file(url = u_msoa, destfile = "data/z.msoa.geojson")
## read simple features from the data source name (dsn) data/...
#z = st_read(dsn = "data/z.lsoa.geojson")
z = st_read(dsn = "data/z.msoa.geojson")
```

```{r}
# filter Leeds
z_Leeds = filter (z, lad_name == "Leeds")
```

```{r}
# Selecion of variables
z_Leeds = z_Leeds %>% 
  select(geo_code, avslope_perc_u10km, geometry)
```

```{r}
# load cycleway infrastrucure dataset
cycleway = st_read(dsn = "data/cycleway.geojson")
## create length_m of links variable
cycleway$length_m = as.numeric(st_length(cycleway))
```

```{r}
## joining length cycleway
z_Leeds$length_cycleway = aggregate(cycleway["length_m"], z_Leeds, FUN = sum)$length_m
```

```{r}
## replace NA by 0
z_Leeds$length_cycleway[is.na(z_Leeds$length_cycleway)] <- 0
```

```{r Creation PCT dataset, eval=FALSE, include=FALSE}
z_Leeds$geometry <-NULL

names(z_Leeds)[names(z_Leeds) == 'geo_code'] <- 'id'
names(z_Leeds)[names(z_Leeds) == 'avslope_perc_u10km'] <- 'Hilliness'

PCT_Leeds = z_Leeds
write.csv(PCT_Leeds, file = "PCT.csv")
```

```{r Creation geometry dataset, eval=FALSE, include=FALSE}
z_Leeds$avslope_perc_u10km <-NULL
z_Leeds$length_m_cycleway <- NULL
geometry_LSOA = z_Leeds
write.csv(geometry_LSOA, file = "geometry_LSOA.csv")
```

```{r include=FALSE}
# activate basemaps
tmap_mode("view")
```

```{r}
## map deprivation in SLP
#qtm(z_Leeds, "length_cycleway", basemaps = c("OpenStreetMap.BlackAndWhite", "Thunderforest.OpenCycleMap", "HikeBike.HillShading"), fill.palette="Blues")
```

```{r}
Adult_lifestage = read.csv("data/MSOA/Adult lifestage.csv")
Car_or_van_availability = read.csv("data/MSOA/Car or van availability.csv")
Distance_travelled_to_work = read.csv("data/MSOA/Distance travelled to work.csv")
Ethnic_group = read.csv("data/MSOA/Ethnic group.csv")
General_health = read.csv("data/MSOA/General health.csv")
Highest_level_of_qualification = read.csv("data/MSOA/Highest level of qualification.csv")
Households_by_deprivation_dimensions = read.csv("data/MSOA/Households by deprivation dimensions.csv")
Method_of_travel_to_work = read.csv("data/MSOA/Method of travel to work.csv")
Population_density = read.csv("data/MSOA/Population density.csv")
Religion = read.csv("data/MSOA/Religion.csv")
Ward = read.csv("data/MSOA_2011_to_WLAD.csv")
```

```{r}
names(z_Leeds)[names(z_Leeds) == 'geo_code'] <- 'geography.code'

z_Leeds = inner_join(z_Leeds, Adult_lifestage)
z_Leeds = inner_join(z_Leeds, Car_or_van_availability)
z_Leeds = inner_join(z_Leeds, Distance_travelled_to_work)
z_Leeds = inner_join(z_Leeds, Ethnic_group)
z_Leeds = inner_join(z_Leeds, General_health)
z_Leeds = inner_join(z_Leeds, Highest_level_of_qualification)
z_Leeds = inner_join(z_Leeds, Households_by_deprivation_dimensions)
z_Leeds = inner_join(z_Leeds, Method_of_travel_to_work)
z_Leeds = inner_join(z_Leeds, Population_density)
z_Leeds = inner_join(z_Leeds, Religion)
z_Leeds = inner_join(z_Leeds, Ward)
```

```{r census data set creation, eval=FALSE, include=FALSE}
## Clean for Python (just census)

names(z_Leeds)[names(z_Leeds) == 'geography.code'] <- 'id'
names(z_Leeds)[names(z_Leeds) == 'WD16NM'] <- 'Ward_name'

z_Leeds$avslope_perc_u10km <- NULL
z_Leeds$length_cycleway <- NULL
z_Leeds$date <- NULL
z_Leeds$geography <- NULL
z_Leeds$Rural.Urban <- NULL
z_Leeds$geometry <- NULL
z_Leeds$MSOA11NM <- NULL				
z_Leeds$WD16CD <- NULL
z_Leeds$LAD16CD <- NULL
z_Leeds$LAD16NM <- NULL
  
z = z_Leeds

write.csv(z, file = "2011_census.msoa.csv")
```

```{r}
# load LSOA boundaries
## shortname for the url
g_lsoa = "https://opendata.arcgis.com/datasets/da831f80764346889837c72508f046fa_3.geojson"
download.file(url = g_lsoa, destfile = "data/z.da831f80764346889837c72508f046fa_3.geojson")
## read simple features from the data source name (dsn) data/...
geometry = st_read(dsn = "data/z.da831f80764346889837c72508f046fa_3.geojson")
```

```{r}
## map deprivation in SLP
#qtm(z, "median_age", basemaps = c("OpenStreetMap.BlackAndWhite", "Thunderforest.OpenCycleMap", "HikeBike.HillShading"))
```